### ISSUE TITLE
Unable to run the app

### ISSUE THREAD

**Issue by FrankMejzlik** [aftabrehan/board-wex#3]
Dear author, 

I am trying to run this application but I cannot make it work. Potentially, the README could need some more instructions. I followed the few commands that are listed there plus some additional tweaking but without any success.
 
* All ENV variables set to valid projects and URLs
* the Convex project is up and running (no tables, function tho)
* Clerk with JWT template set up

The app starts, I am able to sign in e.g. via Google, then the app throws `app-index.js:33 Failed to authenticate: "No auth provider found matching the given token", check your server auth config` After "User" message sent via WS to the Convex. 

![image](https://github.com/user-attachments/assets/3bfc75dc-6c3c-407d-9302-27ab3c9853ac)

The Convex dashboard shows nothing in logs though. There are no functions or authentication provider in the dashboard either. Isn't there some missing piece of configuring the database in the Convex project or something? The command `npx convex dev` shows this and then terminates.
```sh
$ npx convex dev
⠋ Preparing Convex functions...
⠼ Preparing Convex functions...
```
The directory `convex` is filled with files that seem like a stuff that should initialize the database but it doesn't happen.

What are the next steps to make the authentication and app work?

Thanks for your work and help!
Frank

**Comment by FrankMejzlik** [comment]
OK, the problem is the `convex/tsconfig.json` file. It causes `npm convex dev` to terminate without any errors while it should remain running. After deleting that I am able to run the app.

**Comment by aftabrehan** [comment]
Amazing! I guess your issue is resolved. If you stuck with anything else, let me know; will see.
